### ISSUE TITLE
citation de jurisprudence

### ISSUE THREAD

**Issue by BalanGaetan** [urfistbordeaux/csl_ed_droit_ubx#39]
Je n'ai pas trouvé comment utilisé l'option affaire  en coordination avec le style de bordeaux. Il est toutefois possible de citer correctement la jurisprudence avec le style "projet de loi" comme un traité ou une loi, le test sur une affaire récente de la CJUE donne le résultat suivant : COUR DE JUSTICE DE L’UNION EUROPÉENNE, Conseil de l’Union européenne contre Commission européenne, Arrêt de la Cour Grande Chambre C-73/14, 6 octobre 2015, [consulté le 15 janvier 2019]. 

Est-ce que quelqu'un aurait trouvé un autre solution ?

**Comment by fflamerie** [comment]
Merci pour votre commentaire et pour avoir référencé l'exemple correspondant dans la bibliothèque de groupe - [voir le document dans la bibliothèque de groupe](https://www.zotero.org/groups/2190104/items/YSUTE6LU).  
Nous allons prochainement indiquer comment soumettre une demande d'augmentation du guide, _i. e._ proposer la prise en charge d'un nouveau type de document, en cohérence bien sûr avec les consignes existantes et la logique des règles définies dans le guide.

**Comment by fflamerie** [comment]
voir [issue #40](https://github.com/urfistbordeaux/csl_ed_droit_ubx/issues/40)
