### ISSUE TITLE
Nouveau type de document : jurisprudence

### ISSUE THREAD

**Issue by fflamerie** [urfistbordeaux/csl_ed_droit_ubx#40]
## Jurisprudence
Type de document Zotero = Affaire
Voir : https://documentation-style-csl-ed-droit-ubx.readthedocs.io/en/latest/notes.html#abreviations-conseillees-juridictions

### Modèle pour la bibliographie

Tribunal, Date de décision [JJ mois AAAA], n° N° de requête, _Nom de l’affaire_, Recueil, vol. Volume de recueil-Première page, numéro ECLI.

### Modèle pour les notes de bas de page

Tribunal, Date de décision [JJ mois AAAA], n° N° de requête, _Titre abrégé_.

### Exemple pour la bibliographie

CJUE (Grande Chambre), 6 octobre 2015, n° C-73/14, _Conseil de l'Union européenne contre Commission_, Recueil de jurisprudence, vol. 1982-00417, ECLI:EU:C:2015:663.

### Exemple pour les notes de bas de page

CJUE (Grande Chambre), 6 octobre 2015, n° C-73/14, _Conseil de l'Union européenne contre Commission_.

[Exemple dans la bibliothèque Zotero](https://www.zotero.org/groups/style_csl_ed_droit_bx/items/itemKey/UP7L45FD)

### Notes
* Titre abrégé = nom des parties. En l'absence de titre abrégé, on n'affiche rien en note de bas de page, _i. e._ on ne substitue pas le `Titre abrégé`par le `Nom de l'affaire`.
* Contenu du champ `Extra` = numéro ECLI
* Le modèle des notes de bas de page suit exactement les recommandations du guide.
* Le guide prévoit de ne pas faire figurer la jurisprudence en bibliographie. Lorsque l'on utilise Zotero, il n'est toutefois pas possible d'omettre dans la bibliographie des références citées, voir la discussion [CSL allow dropping items from bibliography](https://forums.zotero.org/discussion/64871/csl-allow-dropping-items-from-bibliography) sur le forum Zotero. Conséquence : le gain de pouvoir utiliser Zotero pour citer la jurisprudence a pour contrepartie la nécessité de supprimer manuellement de la bibliographie toutes les références de type "Affaire". Afin de minimiser cet inconvénient pour les utilisateurs, on propose de paramétrer le style pour rassembler toutes les "Affaires" dans une section distincte, sur le modèle de ce qui est fait pour la liste de ressources et la bibliographie - voir [la rubrique "Liste de ressources et bibliographie" dans la documentation du style ](https://documentation-style-csl-ed-droit-ubx.readthedocs.io/en/latest/notes.html#liste-de-ressources-et-bibliographie). Il suffit ainsi de supprimer toute cette section. 
:warning: La suppression est à effectuer :
* en tout dernier lieu lorsque plus aucune modification n’est effectuée dans le document ;
* sur une copie du fichier après suppression des codes de champ Zotero ; il est plus que recommandable de conserver une version du fichier avec les codes de champ et la bibliographie complète - voir la page [Utiliser le module Zotero pour Word de la documentation Zotero](https://www.zotero.org/support/fr/word_processor_plugin_usage).

Merci @BalanGaetan pour la contribution à la rédaction de cette issue!

**Comment by fflamerie** [comment]
Voici une première version du fichier .csl mis à jour. [universite-de-bordeaux-ecole-doctorale-de-droit-jurisprudence.zip](https://github.com/urfistbordeaux/csl_ed_droit_ubx/files/3545144/universite-de-bordeaux-ecole-doctorale-de-droit-jurisprudence.zip)
Difficulté concernant la saisie du numéro ECLI dans le champ `Extra` : Zotero doit interpréter le `ECLI: ` comme un préfixe de variable - voir [Citing fields from Extra](https://www.zotero.org/support/kb/item_types_and_fields#citing_fields_from_extra) - et n'affiche rien. 2 options possibles:
* option1 : modifier la saisie dans le champ `Extra` - fait dans la bibliothèque Zotero en ajoutant des [ ]
* option2 : saisir le numéro ECLI dans un autre champ, le moins pire serait probablement le champ `Histoire` - à vrai dire il n'y a pas vraiment d'autre option

**Comment by BalanGaetan** [comment]
Bonjour Frédérique,

Merci beaucoup pour cette solution c'est vraiment enfin je n'ai pas de mots
approprié pour ma reconnaissance a quelques semaine du rendu final de mon
manuscrit
Je ne pouvais pas espérer mieux.

Bien à vous,

Gaëtan
Gaëtan Balan
Doctorant en Droit
Centre de Droit Maritime et Océanique
+336 50 57 00 16
fr.linkedin.com/in/gaetanbalan/

**Comment by fflamerie** [comment]
Fait, avec l'option 2 pour le numéro ECLI
